export const DATA = [
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
        { minute: 5, value: -80 },
        { minute: 6, value: -4 },
        { minute: 7, value: 60 },
        { minute: 8, value: 28 },
        { minute: 9, value: -100 },
        { minute: 10, value: 100 },
        { minute: 11, value: 56 },
        { minute: 12, value: -4 },
        { minute: 13, value: -100 },
        { minute: 14, value: 14 },
        { minute: 15, value: -14 },
        { minute: 16, value: 34 },
        { minute: 17, value: 96 },
        { minute: 18, value: 8 },
        { minute: 19, value: 12 },
        { minute: 20, value: -52 },
        { minute: 21, value: 40 },
        { minute: 22, value: 44 },
        { minute: 23, value: 74 },
        { minute: 24, value: 86 },
        { minute: 25, value: -20 },
        { minute: 26, value: 32 },
        { minute: 27, value: 50 },
        { minute: 28, value: 0 },
        { minute: 29, value: 0 },
        { minute: 30, value: 22 },
        { minute: 31, value: 74 },
        { minute: 32, value: 44 },
        { minute: 33, value: -34 },
        { minute: 34, value: -100 },
        { minute: 35, value: 100 },
        { minute: 36, value: -32 },
        { minute: 37, value: -28 },
        { minute: 38, value: 0 },
        { minute: 39, value: 100 },
        { minute: 40, value: 42 },
        { minute: 41, value: 24 },
        { minute: 42, value: 0 },
        { minute: 43, value: -72 },
        { minute: 44, value: -42 },
        { minute: 45, value: -28 },
        { minute: 46, value: 36 },
        { minute: 47, value: 6 },
        { minute: 48, value: 22 },
        { minute: 49, value: 36 },
        { minute: 50, value: -24 },
        { minute: 51, value: 40 },
        { minute: 52, value: 10 },
        { minute: 53, value: 84 },
        { minute: 54, value: -24 },
        { minute: 55, value: -22 },
        { minute: 56, value: 100 },
        { minute: 57, value: 72 },
        { minute: 58, value: 90 },
        { minute: 59, value: -100 },
        { minute: 60, value: -56 },
        { minute: 61, value: -100 },
        { minute: 62, value: -20 },
        { minute: 63, value: 90 },
        { minute: 64, value: -26 },
        { minute: 65, value: -32 },
        { minute: 66, value: 100 },
        { minute: 67, value: -42 },
        { minute: 68, value: -66 },
        { minute: 69, value: -76 },
        { minute: 70, value: -20 },
        { minute: 71, value: 0 },
        { minute: 72, value: 90 },
        { minute: 73, value: 66 },
        { minute: 74, value: -100 },
        { minute: 75, value: -76 },
        { minute: 76, value: 100 },
        { minute: 77, value: 0 },
        { minute: 78, value: -76 },
        { minute: 79, value: -62 },
        { minute: 80, value: 62 },
        { minute: 81, value: -58 },
        { minute: 82, value: -20 },
        { minute: 83, value: 40 },
        { minute: 84, value: 100 },
        { minute: 85, value: 18 },
        { minute: 86, value: 90 },
        { minute: 87, value: 100 },
        { minute: 88, value: -72 },
        { minute: 89, value: -30 },
        { minute: 90, value: 72 },
        { minute: 91, value: 32 },
        { minute: 92, value: 14 },
      ],
    },
    message: "",
  },
  {
    code: 1,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: 68 },
        { minute: 2, value: 20 },
        { minute: 3, value: -46 },
        { minute: 4, value: -18 },
        { minute: 5, value: 16 },
        { minute: 6, value: 0 },
        { minute: 7, value: 60 },
        { minute: 8, value: -20 },
        { minute: 9, value: 80 },
        { minute: 10, value: 80 },
        { minute: 11, value: 100 },
        { minute: 12, value: 76 },
        { minute: 13, value: 0 },
        { minute: 14, value: -34 },
        { minute: 15, value: 54 },
        { minute: 16, value: 88 },
        { minute: 17, value: 72 },
        { minute: 18, value: 14 },
        { minute: 19, value: 100 },
        { minute: 20, value: 0 },
        { minute: 21, value: 100 },
        { minute: 22, value: 70 },
        { minute: 23, value: 66 },
        { minute: 24, value: 100 },
        { minute: 25, value: 66 },
        { minute: 26, value: 100 },
        { minute: 27, value: 42 },
        { minute: 28, value: 84 },
        { minute: 29, value: 32 },
        { minute: 30, value: 20 },
        { minute: 31, value: -20 },
        { minute: 32, value: 80 },
        { minute: 33, value: 100 },
        { minute: 34, value: 14 },
        { minute: 35, value: 0 },
        { minute: 36, value: 100 },
        { minute: 37, value: -20 },
        { minute: 38, value: 50 },
        { minute: 39, value: 74 },
        { minute: 40, value: 72 },
        { minute: 41, value: -78 },
        { minute: 42, value: 52 },
        { minute: 43, value: 74 },
        { minute: 44, value: 86 },
        { minute: 45, value: 50 },
        { minute: 46, value: -46 },
        { minute: 47, value: 22 },
        { minute: 48, value: 100 },
        { minute: 49, value: 0 },
        { minute: 50, value: -80 },
        { minute: 51, value: -34 },
        { minute: 52, value: -16 },
        { minute: 53, value: 0 },
        { minute: 54, value: 100 },
        { minute: 55, value: 80 },
        { minute: 56, value: 60 },
        { minute: 57, value: 0 },
        { minute: 58, value: -12 },
        { minute: 59, value: 32 },
        { minute: 60, value: 86 },
        { minute: 61, value: 68 },
        { minute: 62, value: -50 },
        { minute: 63, value: 30 },
        { minute: 64, value: 100 },
        { minute: 65, value: 100 },
        { minute: 66, value: -10 },
        { minute: 67, value: 0 },
        { minute: 68, value: -76 },
        { minute: 69, value: -50 },
        { minute: 70, value: 4 },
        { minute: 71, value: 0 },
        { minute: 72, value: 0 },
        { minute: 73, value: 0 },
        { minute: 74, value: 54 },
        { minute: 75, value: 88 },
        { minute: 76, value: -36 },
        { minute: 77, value: 50 },
        { minute: 78, value: 32 },
        { minute: 79, value: 76 },
        { minute: 80, value: 84 },
        { minute: 81, value: 100 },
        { minute: 82, value: -8 },
        { minute: 83, value: 22 },
        { minute: 84, value: 0 },
        { minute: 85, value: 80 },
        { minute: 86, value: 32 },
        { minute: 87, value: 80 },
        { minute: 88, value: 0 },
        { minute: 89, value: 100 },
        { minute: 90, value: -94 },
        { minute: 91, value: -8 },
        { minute: 92, value: 74 },
      ],
    },
    message: "",
  },
];

export const DATA_I = [
  {
    code: 1,
    data: {
      incidents: [
        { text: "FT", incidentType: "period", homeScore: 2, awayScore: 0 },
        {
          text: "",
          confirmed: null,
          time: 90,
          incidentType: "card",
          player: {
            id: "9zuz9pl88j8ni6u",
            name: "Sergio Peña",
            slug: "sergio-pena",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
          addedTime: 4,
        },
        {
          text: "",
          confirmed: null,
          time: 88,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          homeScore: 2,
          awayScore: 0,
          time: 86,
          incidentType: "goal",
          player: {
            id: "7xdat6lc5ygr35v",
            name: "Lautaro Martínez",
            slug: "lautaro-martinez",
          },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: null,
          playerOut: null,
          assist1: {
            id: "o8tzjgl1lx11w47",
            name: "Enzo Jeremias Fernández",
            slug: "enzo-jeremias-fernandez",
          },
        },
        {
          text: "",
          confirmed: null,
          time: 83,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "o8tzjgl76y8s006",
            name: "Lucas Martinez Quarta",
            slug: "lucas-martinez-quarta",
          },
          playerOut: {
            id: "q69zrnllgo2rah5",
            name: "Germán Pezzella",
            slug: "german-pezzella",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 77,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "sybadnlnf68sdt6",
            name: "Christian Cueva",
            slug: "christian-cueva",
          },
          playerOut: {
            id: "o6jamrl0rz5kw7q",
            name: "Marcos López",
            slug: "marcos-lopez",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 77,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "ykcv4il5ry4s1xj",
            name: "Guido Rodríguez",
            slug: "guido-rodriguez",
          },
          playerOut: {
            id: "623z28lcsjzrt8p",
            name: "Leandro Paredes",
            slug: "leandro-paredes",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 77,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "q69zrnl596h4vee",
            name: "Valentin Carboni",
            slug: "valentin-carboni",
          },
          playerOut: {
            id: "54cvbml0sdbrl7t",
            name: "Ángel Di María",
            slug: "angel-di-maria",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          homeScore: 1,
          awayScore: 0,
          time: 72,
          incidentType: "inGamePenalty",
          player: {
            id: "623z28lcsjzrt8p",
            name: "Leandro Paredes",
            slug: "leandro-paredes",
          },
          sequence: null,
          isHome: true,
          incidentClass: "missed",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 67,
          incidentType: "card",
          player: {
            id: "623z28lcsjzrt8p",
            name: "Leandro Paredes",
            slug: "leandro-paredes",
          },
          sequence: null,
          isHome: true,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 66,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "5z3v0blqllmevu6",
            name: "Nicolás González",
            slug: "nicolas-gonzalez",
          },
          playerOut: {
            id: "gk7aeqln2j81v0f",
            name: "Alejandro Garnacho",
            slug: "alejandro-garnacho",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 66,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "o8tzjgl1lx11w47",
            name: "Enzo Jeremias Fernández",
            slug: "enzo-jeremias-fernandez",
          },
          playerOut: {
            id: "7xdat6l14phr35v",
            name: "Giovani Lo Celso",
            slug: "giovani-lo-celso",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 63,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "n97akmlffx4mwnv",
            name: "Franco Zanelatto",
            slug: "franco-zanelatto",
          },
          playerOut: {
            id: "q69zrnl5mec8vee",
            name: "Roberto Reyna",
            slug: "roberto-reyna",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 56,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "cq0afil4159r31c",
            name: "Gianluca Lapadula",
            slug: "gianluca-lapadula",
          },
          playerOut: {
            id: "c467w80ol6mrt8p",
            name: "Paolo Guerrero",
            slug: "paolo-guerrero",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 56,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "1ztvu6lrw767v9p",
            name: "José Rivera",
            slug: "jose-rivera",
          },
          playerOut: {
            id: "a8qv3rlv4xan7fj",
            name: "Edison Flores",
            slug: "edison-flores",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 53,
          incidentType: "card",
          player: {
            id: "a8qv3rlv4xan7fj",
            name: "Edison Flores",
            slug: "edison-flores",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          homeScore: 1,
          awayScore: 0,
          time: 47,
          incidentType: "goal",
          player: {
            id: "7xdat6lc5ygr35v",
            name: "Lautaro Martínez",
            slug: "lautaro-martinez",
          },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: null,
          playerOut: null,
          assist1: {
            id: "54cvbml0sdbrl7t",
            name: "Ángel Di María",
            slug: "angel-di-maria",
          },
        },
        {
          text: "",
          confirmed: null,
          time: 45,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "ykcv4ilq15nxw5u",
            name: "Jesús Castillo",
            slug: "jesus-castillo",
          },
          playerOut: {
            id: "a8qv3rl79omn7fj",
            name: "Wilder Cartagena",
            slug: "wilder-cartagena",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "HT",
          time: 45,
          incidentType: "period",
          homeScore: 0,
          awayScore: 0,
        },
        {
          text: "",
          confirmed: null,
          time: 36,
          incidentType: "card",
          player: {
            id: "a8qv3rl79omn7fj",
            name: "Wilder Cartagena",
            slug: "wilder-cartagena",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 28,
          incidentType: "card",
          player: {
            id: "c467w80ol6mrt8p",
            name: "Paolo Guerrero",
            slug: "paolo-guerrero",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
      ],
      corners: [],
    },
    message: "",
  },
  {
    code: 1,
    data: {
      incidents: [
        { text: "FT", incidentType: "period", homeScore: 1, awayScore: 2 },
        {
          text: "",
          confirmed: null,
          time: 88,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "gk7aeqlufesfv0f",
            name: "Maxim Mateas",
            slug: "maxim-mateas",
          },
          playerOut: {
            id: "n97akmlf700sjyf",
            name: "Július Szöke",
            slug: "julius-szoke",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          homeScore: 1,
          awayScore: 2,
          time: 86,
          incidentType: "goal",
          player: {
            id: "sybadnl666s5whq",
            name: "B. Compaore",
            slug: "b.-compaore",
          },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: null,
          playerOut: null,
          assist1: {
            id: "q69zrnlet3qwvee",
            name: "Masaaki Takahara",
            slug: "masaaki-takahara",
          },
        },
        {
          text: "",
          confirmed: null,
          time: 85,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "o6jamrlche13w7q",
            name: "B. Ilievski",
            slug: "b.-ilievski",
          },
          playerOut: {
            id: "6hqac9lv0x2rihp",
            name: "Nikola Vlajkovic",
            slug: "nikola-vlajkovic",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 72,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "sybadnl666s5whq",
            name: "B. Compaore",
            slug: "b.-compaore",
          },
          playerOut: {
            id: "b1ta1llltkzrbib",
            name: "Marjan Radeski",
            slug: "marjan-radeski",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 72,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "q69zrnlet3qwvee",
            name: "Masaaki Takahara",
            slug: "masaaki-takahara",
          },
          playerOut: {
            id: "go6v7il176zntnv",
            name: "Besart Ibraimi",
            slug: "besart-ibraimi",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 69,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "b1ta1llldpzrbib",
            name: "Kyriakos Savvidis",
            slug: "kyriakos-savvidis",
          },
          playerOut: {
            id: "o6jamrlcxdg9w7q",
            name: "David Strelec",
            slug: "david-strelec",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 69,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "5z3v0bln4o0xvu6",
            name: "Zuberu Sharani",
            slug: "zuberu-sharani",
          },
          playerOut: {
            id: "n97akmlc8nasjyf",
            name: "Vladimír Weiss",
            slug: "vladimir-weiss",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 68,
          incidentType: "card",
          player: {
            id: "b1ta1llls4blvff",
            name: "Effiong Hogan Ukpa",
            slug: "effiong-hogan-ukpa",
          },
          sequence: null,
          isHome: true,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 65,
          incidentType: "card",
          player: {
            id: "o6jamrlue5as3t6",
            name: "Stefan Jevtoski",
            slug: "stefan-jevtoski",
          },
          sequence: null,
          isHome: true,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 57,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "7xdat6l1dvnr35v",
            name: "Marko Tolić",
            slug: "marko-tolic",
          },
          playerOut: {
            id: "623z28lvtnhrt8p",
            name: "Róbert Mak",
            slug: "robert-mak",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 57,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: {
            id: "ykcv4il54vsow5u",
            name: "Nino Marcelli",
            slug: "nino-marcelli",
          },
          playerOut: {
            id: "6hqac9lv04srihp",
            name: "Matúš Vojtko",
            slug: "matus-vojtko",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 47,
          incidentType: "card",
          player: {
            id: "o6jamrlcxdg9w7q",
            name: "David Strelec",
            slug: "david-strelec",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 45,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "b1ta1llls4blvff",
            name: "Effiong Hogan Ukpa",
            slug: "effiong-hogan-ukpa",
          },
          playerOut: {
            id: "sybadnlntdysdt6",
            name: "Kire Ristevski",
            slug: "kire-ristevski",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 45,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "gk7aeqlfh9g4v0f",
            name: "Lanre·Kehinde",
            slug: "lanrekehinde",
          },
          playerOut: {
            id: "6hqac9lfh64hvme",
            name: "A. Vosha",
            slug: "a.-vosha",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "HT",
          time: 45,
          incidentType: "period",
          homeScore: 0,
          awayScore: 2,
        },
        {
          text: "",
          confirmed: null,
          time: 48,
          incidentType: "card",
          player: {
            id: "n97akml5xxysjyf",
            name: "Besart Krivanjeva",
            slug: "besart-krivanjeva",
          },
          sequence: null,
          isHome: true,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          homeScore: 0,
          awayScore: 2,
          time: 33,
          incidentType: "goal",
          player: {
            id: "sybadnlntdysdt6",
            name: "Kire Ristevski",
            slug: "kire-ristevski",
          },
          sequence: null,
          isHome: false,
          incidentClass: "ownGoal",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 14,
          incidentType: "card",
          player: { id: "6hqac9lfh64hvme", name: "A. Vosha", slug: "a.-vosha" },
          sequence: null,
          isHome: true,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          homeScore: 0,
          awayScore: 1,
          time: 9,
          incidentType: "goal",
          player: {
            id: "n97akmlc8nasjyf",
            name: "Vladimír Weiss",
            slug: "vladimir-weiss",
          },
          sequence: null,
          isHome: false,
          incidentClass: "regular",
          playerIn: null,
          playerOut: null,
          assist1: {
            id: "o6jamrlcxdg9w7q",
            name: "David Strelec",
            slug: "david-strelec",
          },
        },
      ],
      corners: [
        {
          text: "",
          confirmed: null,
          time: 74,
          incidentType: "corner",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 41,
          incidentType: "corner",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 24,
          incidentType: "corner",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 13,
          incidentType: "corner",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: false,
          incidentClass: "",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
      ],
    },
    message: "",
  },
];


export const DATA_TIMELINE = [
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
        { minute: 5, value: -80 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
        { minute: 5, value: -80 },
        { minute: 6, value: -4 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
        { minute: 5, value: -80 },
        { minute: 6, value: -4 },
        { minute: 7, value: 60 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
        { minute: 5, value: -80 },
        { minute: 6, value: -4 },
        { minute: 7, value: 60 },
        { minute: 8, value: 28 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
        { minute: 5, value: -80 },
        { minute: 6, value: -4 },
        { minute: 7, value: 60 },
        { minute: 8, value: 28 },
        { minute: 9, value: -100 },
      ]
    }
  },
  {
    code: 3,
    data: {
      periodCount: 2,
      periodTime: 45,
      graphPoints: [
        { minute: 1, value: -34 },
        { minute: 2, value: 56 },
        { minute: 3, value: -74 },
        { minute: 4, value: 66 },
        { minute: 5, value: -80 },
        { minute: 6, value: -4 },
        { minute: 7, value: 60 },
        { minute: 8, value: 28 },
        { minute: 9, value: -100 },
        { minute: 10, value: 100 },
      ]
    }
  },
];

export const DATA_EVENT = [
  {
    code: 1,
    data: {
      incidents: [
        {
          text: "",
          confirmed: null,
          time: 1,
          incidentType: "card",
          player: {
            id: "9zuz9pl88j8ni6u",
            name: "Sergio Peña",
            slug: "sergio-pena",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
          addedTime: 4,
        },
      ],
    }
  },
  {
    code: 1,
    data: {
      incidents: [
        {
          text: "",
          confirmed: null,
          time: 1,
          incidentType: "card",
          player: {
            id: "9zuz9pl88j8ni6u",
            name: "Sergio Peña",
            slug: "sergio-pena",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
          addedTime: 4,
        },
        {
          text: "",
          confirmed: null,
          time: 2,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
      ],
    }
  },
  {
    code: 1,
    data: {
      incidents: [
        {
          text: "",
          confirmed: null,
          time: 1,
          incidentType: "card",
          player: {
            id: "9zuz9pl88j8ni6u",
            name: "Sergio Peña",
            slug: "sergio-pena",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
          addedTime: 4,
        },
        {
          text: "",
          confirmed: null,
          time: 2,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 3,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
      ],
    }
  },
  {
    code: 1,
    data: {
      incidents: [
        {
          text: "",
          confirmed: null,
          time: 1,
          incidentType: "card",
          player: {
            id: "9zuz9pl88j8ni6u",
            name: "Sergio Peña",
            slug: "sergio-pena",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
          addedTime: 4,
        },
        {
          text: "",
          confirmed: null,
          time: 2,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 3,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 4,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "o8tzjgl76y8s006",
            name: "Lucas Martinez Quarta",
            slug: "lucas-martinez-quarta",
          },
          playerOut: {
            id: "q69zrnllgo2rah5",
            name: "Germán Pezzella",
            slug: "german-pezzella",
          },
          assist1: { id: "", name: "", slug: "" },
        },
      ],
    }
  },
  {
    code: 1,
    data: {
      incidents: [
        {
          text: "",
          confirmed: null,
          time: 1,
          incidentType: "card",
          player: {
            id: "9zuz9pl88j8ni6u",
            name: "Sergio Peña",
            slug: "sergio-pena",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
          addedTime: 4,
        },
        {
          text: "",
          confirmed: null,
          time: 2,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 3,
          incidentType: "card",
          player: {
            id: "sybadnlnrxrsdt6",
            name: "Carlos Zambrano",
            slug: "carlos-zambrano",
          },
          sequence: null,
          isHome: false,
          incidentClass: "yellow",
          playerIn: null,
          playerOut: null,
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 4,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "o8tzjgl76y8s006",
            name: "Lucas Martinez Quarta",
            slug: "lucas-martinez-quarta",
          },
          playerOut: {
            id: "q69zrnllgo2rah5",
            name: "Germán Pezzella",
            slug: "german-pezzella",
          },
          assist1: { id: "", name: "", slug: "" },
        },
        {
          text: "",
          confirmed: null,
          time: 5,
          incidentType: "substitution",
          player: { id: "", name: "", slug: "" },
          sequence: null,
          isHome: true,
          incidentClass: "regular",
          playerIn: {
            id: "o8tzjgl76y8s006",
            name: "Lucas Martinez Quarta",
            slug: "lucas-martinez-quarta",
          },
          playerOut: {
            id: "q69zrnllgo2rah5",
            name: "Germán Pezzella",
            slug: "german-pezzella",
          },
          assist1: { id: "", name: "", slug: "" },
        },
      ],
    }
  },
]