export const optionsLanguage = [
  { id: 1, name: 'Português (Brasil)', link: '/images/languages-flag/br.svg', alt: 'pt-BR' },
  { id: 2, name: 'English (US)', link: '/images/languages-flag/en.svg', alt: 'en' },
  { id: 3, name: 'English (UK)', link: '/images/languages-flag/en-GB.svg', alt: 'en-GB' },
  { id: 4, name: 'Philippines (English)', link: '/images/languages-flag/ph.svg', alt: 'en-PH' },
  { id: 5, name: 'Singapore (English)', link: '/images/languages-flag/sg.svg', alt: 'en-SG' },
  { id: 6, name: 'India (English)', link: '/images/languages-flag/hi.svg', alt: 'en-IN' },
  { id: 7, name: 'Português', link: '/images/languages-flag/pt.svg', alt: 'pt' },
  { id: 8, name: 'Español', link: '/images/languages-flag/es.svg', alt: 'es' },
  { id: 9, name: 'Français', link: '/images/languages-flag/fr.svg', alt: 'fr' },
  { id: 10, name: 'Italiano', link: '/images/languages-flag/it.svg', alt: 'it' },
  { id: 11, name: 'Republik Indonesia', link: '/images/languages-flag/id.svg', alt: 'id' },
  { id: 12, name: 'Türkçe', link: '/images/languages-flag/tr.svg', alt: 'tr' },
  { id: 13, name: 'भारत', link: '/images/languages-flag/hi.svg', alt: 'hi' },
  { id: 14, name: 'Языки', link: '/images/languages-flag/ru.svg', alt: 'ru' },
  { id: 15, name: 'Українська', link: '/images/languages-flag/uk.svg', alt: 'uk' },
  { id: 16, name: 'Bahasa Malaysia', link: '/images/languages-flag/my.svg', alt: 'ms' },
  { id: 17, name: 'বাংলা', link: '/images/languages-flag/bd.svg', alt: 'bn' },
  { id: 18, name: 'Hrvatski', link: '/images/languages-flag/hr.svg', alt: 'hr' },
  { id: 19, name: 'Nederlands', link: '/images/languages-flag/nl.svg', alt: 'nl' },
  { id: 20, name: 'Język Polski', link: '/images/languages-flag/pl.svg', alt: 'pl' },
  { id: 21, name: 'Ελληνικά', link: '/images/languages-flag/el.svg', alt: 'el' },
  { id: 22, name: 'Deutsch', link: '/images/languages-flag/de.svg', alt: 'de' },
  { id: 23, name: 'عَرَبِيّ', link: '/images/languages-flag/ar-xa.svg', alt: 'ar-XA' },
  { id: 24, name: 'ภาษาไทย', link: '/images/languages-flag/th.svg', alt: 'th' },
  { id: 25, name: '한국어', link: '/images/languages-flag/ko.svg', alt: 'ko' },
  { id: 26, name: '中国话', link: '/images/languages-flag/zh-CN.svg', alt: 'zh-CN' },
  { id: 27, name: '日本語', link: '/images/languages-flag/jp.svg', alt: 'ja' },
  { id: 28, name: 'Tiếng việt', link: '/images/languages-flag/vi.svg', alt: 'vi' },
];